"""drop stale ix_loans_borrower_id index

Revision ID: 188ae37be4aa
Revises: 44f1d47fea97
Create Date: 2026-09-04 00:14:47.317124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188ae37be4aa'
down_revision: Union[str, Sequence[str], None] = '44f1d47fea97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_borrower_id'), table_name='loans')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_loans_borrower_id'), 'loans', ['borrower_id'], unique=False)
    # ### end Alembic commands ###
