"""create all missing tables

Revision ID: 408743feea24
Revises: ac86bb2b864d
Create Date: 2026-09-02 16:45:02.823610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '408743feea24'
down_revision: Union[str, Sequence[str], None] = 'ac86bb2b864d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(conn)

    # Helper to check column existence
    def has_column(table_name: str, column_name: str) -> bool:
        cols = [c['name'] for c in inspector.get_columns(table_name)]
        return column_name in cols

    # Helper to add column if missing
    def add_column_if_missing(table_name: str, column: sa.Column):
        if not has_column(table_name, column.name):
            op.add_column(table_name, column)
            print(f"Added column {column.name} to {table_name}")

    # Helper to create table if missing OR migrate existing table columns/constraints
    # BOOKS
    if 'books' not in inspector.get_table_names():
        op.create_table('books',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=1000), nullable=False),
            sa.Column('author', sa.String(length=1000), nullable=False),
            sa.Column('description', sa.String(length=25000), nullable=False),
            sa.Column('genre', sa.String(length=10000), nullable=False),
            sa.Column('cover_image_path', sa.String(length=200), nullable=True),
            sa.Column('total_copies', sa.Integer(), nullable=False),
            sa.Column('available_copies', sa.Integer(), nullable=False),
            sa.Column('createdAt', sa.DateTime(), nullable=False),
            sa.Column('updatedAt', sa.DateTime(), nullable=False),
            sa.Column('isbn', sa.String(length=20), nullable=False),
            sa.CheckConstraint('available_copies <= total_copies', name='ck_available_copies_le_total_copies'),
            sa.CheckConstraint('available_copies >= 0', name='ck_available_copies_ge_zero'),
            sa.CheckConstraint('total_copies >= 0', name='ck_total_copies_ge_zero'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('isbn')
        )
    else:
        # table exists -> ensure columns present and constraints
        add_column_if_missing('books', sa.Column('title', sa.String(length=1000), nullable=False))
        add_column_if_missing('books', sa.Column('author', sa.String(length=1000), nullable=False))
        add_column_if_missing('books', sa.Column('description', sa.String(length=25000), nullable=False))
        add_column_if_missing('books', sa.Column('genre', sa.String(length=10000), nullable=False))
        add_column_if_missing('books', sa.Column('cover_image_path', sa.String(length=200), nullable=True))
        add_column_if_missing('books', sa.Column('total_copies', sa.Integer(), nullable=False))
        add_column_if_missing('books', sa.Column('available_copies', sa.Integer(), nullable=False))
        add_column_if_missing('books', sa.Column('createdAt', sa.DateTime(), nullable=False))
        add_column_if_missing('books', sa.Column('updatedAt', sa.DateTime(), nullable=False))
        add_column_if_missing('books', sa.Column('isbn', sa.String(length=20), nullable=False))

        # Ensure unique constraint on isbn exists
        uq = [c for c in inspector.get_unique_constraints('books')]
        if not any('isbn' in uc.get('column_names', []) for uc in uq):
            op.create_unique_constraint(op.f('uq_books_isbn'), 'books', ['isbn'])

        # Ensure check constraints exist by name
        checks = [c['name'] for c in inspector.get_check_constraints('books')]
        if 'ck_available_copies_le_total_copies' not in checks:
            op.create_check_constraint('ck_available_copies_le_total_copies', 'books', 'available_copies <= total_copies')
        if 'ck_available_copies_ge_zero' not in checks:
            op.create_check_constraint('ck_available_copies_ge_zero', 'books', 'available_copies >= 0')
        if 'ck_total_copies_ge_zero' not in checks:
            op.create_check_constraint('ck_total_copies_ge_zero', 'books', 'total_copies >= 0')

    existing_ix = [ix['name'] for ix in inspector.get_indexes('books')] 
    if op.f('ix_books_id') not in existing_ix:
        op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)

    # USERS
    if 'users' not in inspector.get_table_names():
        op.create_table('users',
            sa.Column('name', sa.String(length=20), nullable=False),
            sa.Column('role', sa.String(length=20), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('verified_at', sa.DateTime(), nullable=True),
            sa.Column('token', sa.String(length=32), nullable=True),
            sa.Column('createdAt', sa.DateTime(), nullable=False),
            sa.Column('updatedAt', sa.DateTime(), nullable=False),
            sa.Column('genres', sa.String(length=50), nullable=False),
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('email', sa.String(length=320), nullable=False),
            sa.Column('hashed_password', sa.String(length=1024), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('is_superuser', sa.Boolean(), nullable=False),
            sa.Column('is_verified', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    else:
        add_column_if_missing('users', sa.Column('name', sa.String(length=20), nullable=False))
        add_column_if_missing('users', sa.Column('role', sa.String(length=20), nullable=False))
        add_column_if_missing('users', sa.Column('status', sa.String(length=20), nullable=False))
        add_column_if_missing('users', sa.Column('verified_at', sa.DateTime(), nullable=True))
        add_column_if_missing('users', sa.Column('token', sa.String(length=32), nullable=True))
        add_column_if_missing('users', sa.Column('createdAt', sa.DateTime(), nullable=False))
        add_column_if_missing('users', sa.Column('updatedAt', sa.DateTime(), nullable=False))
        add_column_if_missing('users', sa.Column('genres', sa.String(length=50), nullable=False))
        add_column_if_missing('users', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
        add_column_if_missing('users', sa.Column('email', sa.String(length=320), nullable=False))
        add_column_if_missing('users', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
        add_column_if_missing('users', sa.Column('is_active', sa.Boolean(), nullable=False))
        add_column_if_missing('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
        add_column_if_missing('users', sa.Column('is_verified', sa.Boolean(), nullable=False))

        # Ensure email unique exists
        uq_users = [c for c in inspector.get_unique_constraints('users')]
        if not any('email' in uc.get('column_names', []) for uc in uq_users):
            op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])

    existing_ix = [ix['name'] for ix in inspector.get_indexes('users')] 
    if op.f('ix_users_email') not in existing_ix:
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    # CHATS
    if 'chats' not in inspector.get_table_names():
        op.create_table('chats',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('content', sa.String(length=1000000), nullable=True),
            sa.Column('createdAt', sa.DateTime(), nullable=False),
            sa.Column('updatedAt', sa.DateTime(), nullable=False),
            sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    else:
        add_column_if_missing('chats', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
        add_column_if_missing('chats', sa.Column('name', sa.String(length=100), nullable=False))
        add_column_if_missing('chats', sa.Column('content', sa.String(length=1000000), nullable=True))
        add_column_if_missing('chats', sa.Column('createdAt', sa.DateTime(), nullable=False))
        add_column_if_missing('chats', sa.Column('updatedAt', sa.DateTime(), nullable=False))
        add_column_if_missing('chats', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))

        # Ensure FK to users exists (best-effort): if not present, add it
        fks = [fk['constrained_columns'] for fk in inspector.get_foreign_keys('chats')]
        if not any(['user_id'] == fk for fk in fks):
            op.create_foreign_key(op.f('fk_chats_user_id_users'), 'chats', 'users', ['user_id'], ['id'])

    existing_ix = [ix['name'] for ix in inspector.get_indexes('chats')] 
    if op.f('ix_chats_id') not in existing_ix:
        op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)

    # LOANS
    if 'loans' not in inspector.get_table_names():
        op.create_table('loans',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('borrower_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('book_id', sa.Integer(), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('rejection_reason', sa.String(length=200), nullable=True),
            sa.Column('due_date', sa.DateTime(), nullable=True),
            sa.Column('returned_at', sa.DateTime(), nullable=True),
            sa.Column('requested_at', sa.DateTime(), nullable=False),
            sa.Column('approved_at', sa.DateTime(), nullable=True),
            sa.Column('rejected_at', sa.DateTime(), nullable=True),
            sa.CheckConstraint("status != 'pending' OR (due_date IS NULL AND approved_at IS NULL AND returned_at IS NULL AND rejection_reason IS NULL)", name='ck_pending_loan_has_no_resolution_fields'),
            sa.CheckConstraint('approved_at IS NULL OR approved_at >= requested_at', name='ck_approved_at_after_requested_at'),
            sa.CheckConstraint('due_date IS NULL OR due_date >= requested_at', name='ck_due_date_after_requested_at'),
            sa.CheckConstraint('returned_at IS NULL OR returned_at >= requested_at', name='ck_returned_at_after_requested_at'),
            sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
            sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    else:
        add_column_if_missing('loans', sa.Column('id', sa.Integer(), nullable=False))
        add_column_if_missing('loans', sa.Column('borrower_id', postgresql.UUID(as_uuid=True), nullable=False))
        add_column_if_missing('loans', sa.Column('book_id', sa.Integer(), nullable=False))
        add_column_if_missing('loans', sa.Column('status', sa.String(length=20), nullable=False))
        add_column_if_missing('loans', sa.Column('rejection_reason', sa.String(length=200), nullable=True))
        add_column_if_missing('loans', sa.Column('due_date', sa.DateTime(), nullable=True))
        add_column_if_missing('loans', sa.Column('returned_at', sa.DateTime(), nullable=True))
        add_column_if_missing('loans', sa.Column('requested_at', sa.DateTime(), nullable=False))
        add_column_if_missing('loans', sa.Column('approved_at', sa.DateTime(), nullable=True))
        add_column_if_missing('loans', sa.Column('rejected_at', sa.DateTime(), nullable=True))

        # Ensure FKs exist: book_id -> books.id, borrower_id -> users.id
        fks_loans = [fk['constrained_columns'] for fk in inspector.get_foreign_keys('loans')]
        if not any(['book_id'] == fk for fk in fks_loans):
            op.create_foreign_key(op.f('fk_loans_book_id_books'), 'loans', 'books', ['book_id'], ['id'])
        if not any(['borrower_id'] == fk for fk in fks_loans):
            op.create_foreign_key(op.f('fk_loans_borrower_id_users'), 'loans', 'users', ['borrower_id'], ['id'])

    existing_ix = [ix['name'] for ix in inspector.get_indexes('loans')] 
    if op.f('ix_loans_id') not in existing_ix:
        op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)

    # CHAT_MESSAGES
    if 'chat_messages' not in inspector.get_table_names():
        op.create_table('chat_messages',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('chat_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('content', sa.String(length=1000000), nullable=False),
            sa.Column('reply', sa.String(length=1000000), nullable=False),
            sa.Column('createdAt', sa.DateTime(), nullable=False),
            sa.Column('updatedAt', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    else:
        add_column_if_missing('chat_messages', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
        add_column_if_missing('chat_messages', sa.Column('chat_id', postgresql.UUID(as_uuid=True), nullable=False))
        add_column_if_missing('chat_messages', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
        add_column_if_missing('chat_messages', sa.Column('content', sa.String(length=1000000), nullable=False))
        add_column_if_missing('chat_messages', sa.Column('reply', sa.String(length=1000000), nullable=False))
        add_column_if_missing('chat_messages', sa.Column('createdAt', sa.DateTime(), nullable=False))
        add_column_if_missing('chat_messages', sa.Column('updatedAt', sa.DateTime(), nullable=False))

        # Ensure FKs exist for chat_messages
        fks_msgs = [fk['constrained_columns'] for fk in inspector.get_foreign_keys('chat_messages')]
        if not any(['chat_id'] == fk for fk in fks_msgs):
            op.create_foreign_key(op.f('fk_chat_messages_chat_id_chats'), 'chat_messages', 'chats', ['chat_id'], ['id'])
        if not any(['user_id'] == fk for fk in fks_msgs):
            op.create_foreign_key(op.f('fk_chat_messages_user_id_users'), 'chat_messages', 'users', ['user_id'], ['id'])

    existing_ix = [ix['name'] for ix in inspector.get_indexes('chat_messages')] 
    if op.f('ix_chat_messages_id') not in existing_ix:
        op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
